defaults:
  - model: apriori
  - _self_

data:
  raw:
    path: Market Basket Analysis/data/market_basket.csv
    format: csv
    separator: ","
    skip_rows: 1
    header: None

logs:
  path: Market Basket Analysis/logs/
  fileFormat: market_basket_analysis_
