defaults:
  - model: apriori
  - hydra/job_logging: colorlog
  - hydra/hydra_logging: colorlog
  - override hydra/job_logging: custom

data:
  raw:
    path: Market Basket Analysis/data/market_basket.csv
    format: csv
    separator: ","
    skip_rows: 1
    header: None

logs:
  path: Market Basket Analysis/logs/
  fileFormat: market_basket_analysis_
